config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  root 'produtos#index'
  post 'produtos/busca', to: 'produtos#busca', as: :busca_produtos
  resources :produtos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :departamento, optional: true

  validates :nome, :preco, :cor, :quantidade, :departamento, presence: true
  validates :nome, length: { in: 4..25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[show edit update destroy]

  # GET /departamentos or /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1 or /departamentos/1.json
  def show
    @produtos = Produto.where('departamento_id like ?', "%#{@departamento.id}%")
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit; end

  # POST /departamentos or /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    if @departamento.save
      flash[:notice] = 'Departamento criado com sucesso.'
      redirect_to departamentos_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /departamentos/1 or /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: 'Departamento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1 or /departamentos/1.json
  # def destroy
  #   @departamento.destroy
  #   respond_to do |format|
  #     format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_departamento
    @departamento = Departamento.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def departamento_params
    params.require(:departamento).permit(:nome)
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_product, only: %i[update edit]
  before_action :set_department, only: %i[update create new edit]
  def index
    @produtos = Produto.order(nome: :desc).limit 5
    @prod_desc = Produto.order(:preco).limit(1)
  end

  def new
    @produto = Produto.new
  end

  def edit; end

  def create
    @produto = Produto.new(produto_params)
    if @produto.save
      flash[:notice] = 'Produto criado com sucesso'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @produto.update(produto_params)
      flash[:notice] = 'Produto atualizado com sucesso!'
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    Produto.destroy params[:id]
    redirect_to root_url
  end

  def show
    @nome = Produto.where('nome like ?', "%#{params[:nome]}%")
  end

  private

  def set_product
    @produto = Produto.find(params[:id])
  end

  def set_department
    @dep = Departamento.all
  end

  def produto_params
    params.require(:produto).permit(:nome, :cor, :preco, :quantidade, :departamento_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>
      <ul>
        <% departamento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group text-center mb-3">
    <%= form.label :nome, class: "form-label my-0 py-0 text-dark"  %>
    <%= form.text_field :nome, class: "form-control  my-0 py-0" %>
  </div>
  <div class="text-center">
    <%= form.submit  class: "mt-1 btn btn-primary"%>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1 class="text-secondary text-center mb-3">Editar Departamento</h1>
<div class="container d-flex justify-content-center flex-column w-25 align-items-center text-secondary ">
  <%= render 'form', departamento: @departamento %>
  <%= link_to 'Back', departamentos_path, class: "badge bg-light text-dark text-decoration-none mt-3" %>
</div>

app/views/departamentos/index.html.erb
<h1 class=" text-center text-secondary">Departamentos</h1>
<div class="container w-50">
  <table class="table table-bordered table-hover mt-1">
    <thead>
      <tr class="text-center">
        <th>Nome</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @departamentos.each do |departamento| %>
        <tr class="text-center">
          <td><%= departamento.nome %></td>
          <td><%= link_to 'Ver produtos', departamento, class: "btn btn-secondary" %></td>
          <td><%= link_to 'Editar', edit_departamento_path(departamento), class: "btn btn-secondary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <%= link_to 'Novo Departamento', new_departamento_path, class: "btn btn-outline-primary " %>
  </div>
</div>
<br>

app/views/departamentos/new.html.erb
<h1 class="text-secondary text-center mb-3">Criar Departamento</h1>
<div class="container d-flex justify-content-center flex-column w-25 align-items-center text-secondary ">
  <%= render 'form', departamento: @departamento %>
  <%= link_to 'Back', departamentos_path, class: "badge bg-light text-dark text-decoration-none mt-3" %>
</div>

app/views/departamentos/show.html.erb
<div class="container text-center">
  <p id="notice"><%= notice %></p>
  <h2 class="text-secondary mt-0 mb-3">
    Departamento:
    <%= @departamento.nome %>
  </h2>
  <%= render 'produtos/produto', obj: @produtos %>
  <%= link_to 'Back', departamentos_path, class: "badge bg-light text-dark  text-decoration-none" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto bg-dark pt-3 d-flex flex-row">
  <div class="container">
    <ul class="nav justify-content-center">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show text-start mt-2" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2 bi" viewBox="0 0 16 16" role="img" aria-label="Success:">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </svg>
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light fixed-top bg-white">
  <div class="d-flex justify-content-between w-100 mx-5 my-1">
    <div>
      <%= link_to "Loja", root_path, class: "px-3 navbar-brand mx-auto text-info" %> <span class="me-3 text-secondary">|</span>
      <%= link_to "Criar produto", new_produto_path, class: "pe-3 navbar-brand mx-auto text-info" %><span class="me-3 text-secondary">|</span>
      <%= link_to "Departamentos", departamentos_path, class: "navbar-brand mx-auto text-info" %>
    </div>
    <div>
      <%= form_with url: busca_produtos_path, class: "d-flex", method: :get do |form| %>
        <%= form.text_field :nome, class: "form-control h-75 mx-2", placeholder: "Buscar Produtos" %>
        <%= form.submit "Buscar", class: "btn btn-outline-info my-auto btn-sm" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>StoreAlura</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column h-100" id="body-nav" >
    <%= render 'layouts/navigation' %>
    <main class="flex-shrink-0 my-0 py-0" id="page-content" >
      <%= render 'layouts/messages'%>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/produtos/_form.html.erb
  <%= render 'shared/errors', obj: @produto %>
<%= form_with(model: @produto, class: "w-50", local: true) do |form|%>
  <div class="form-group">
    <%= form.label :nome, class: "form-label my-0 py-0" %><br />
    <%= form.text_field :nome, class: "form-control my-0 py-0" %><br />
  </div>
  <div class="form-group">
    <%= form.label :departamento, class: "form-label my-0 py-0" %><br />
    <%= form.collection_select :departamento_id, @dep, :id, :nome, {}, class: "form-control my-0 py-0" %><br />
  </div>
  <div class="form-group">
    <%= form.label :cor, class: "form-label my-0 py-0" %><br />
    <%= form.text_field :cor, class: "form-control my-0 py-0" %><br />
  </div>
  <div class="form-group">
    <%= form.label :preco, "Preço", class: "form-label my-0 py-0" %><br />
    <%= form.number_field :preco , step: 0.01, class: "form-control my-0 py-0"%><br />
  </div>
  <div class="form-group ">
    <%= form.label :quantidade, class: "form-label my-0 py-0" %><br />
    <%= form.number_field :quantidade, class: "form-control my-0 py-0" %><br />
  </div>
  <div class="text-center">
    <%= form.submit  class: "mt-1 btn btn-primary" %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<table class="table table-bordered table-hover mt-1">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Preço</th>
      <th>Cor</th>
      <th>Quantidade</th>
      <th>Departamento</th>
      <th colspan="2">
      </tr>
    </thead>
    <tbody>
      <% obj.each do |prod| %>
        <tr class="text-center">
          <td><%= prod.nome %></td>
          <td><%= prod.preco.round(2) %></td>
          <td><%= prod.cor %></td>
          <td><%= prod.quantidade %></td>
          <td><%= prod.departamento.nome %></td>
          <td> <%= link_to "Editar", edit_produto_path(prod), class: "btn btn-outline-primary" %> </td>
          <td> <%= button_to "Deletar", prod, method: :delete, class: "btn btn-outline-danger", data: {confirm: "tem certeza que deseja remover o produto: #{prod.nome}"} %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/produtos/edit.html.erb
<div class="d-flex justify-content-center flex-column">
  <h2 class="text-secondary text-center">Editar Produto</h2>
  <div class="container w-100 d-flex justify-content-center flex-column align-items-center">
    <%= render 'produtos/form' %>
  </div>
</div>

app/views/produtos/index.html.erb
<div class="container w-50 mt-0">
  <h2 class="text-secondary text-center mt-0">Produtos</h2>
  <%= render 'produto', obj: @produtos %>
</div>
<div class="container w-50">
  <div class="alert alert-success " role="alert">
    <h2 class="text-dark text-center">Produtos com Desconto</h2>
  </div>
  <%= render 'produto', obj: @prod_desc%>
</div>

app/views/produtos/new.html.erb
<div class="d-flex justify-content-center flex-column">
  <% if @produto.errors.any? %>
    <div class="container">
      <div class="alert alert-danger alert-dismissible fade show text-start" role="alert">
        Os Seguintes erros impediram a criação:
        <ul>
          <% @produto.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
  <% end %>
  <div class="container w-25">
    <%= form_for @produto do |form| %>
      <h2 class="text-secondary text-center">Criar Produto</h2>
      <hr>
      <div class="form-group">
        <%= form.label :nome, class: "form-label mx-o" %><br />
        <%= form.text_field :nome, class: "form-control" %><br />
      </div>
      <div class="form-group">
        <%= form.label :cor, class: "form-label mx-0" %><br />
        <%= form.text_field :cor, class: "form-control " %><br />
      </div>
      <div class="form-group">
        <%= form.label :preco, "Preço", class: "form-label mx-0" %><br />
        <%= form.number_field :preco , step: 0.01, class: "form-control"%><br />
      </div>
      <div class="form-group">
        <%= form.label :quantidade, class: "form-label mx-0" %><br />
        <%= form.number_field :quantidade, class: "form-control" %><br />
      </div>
      <%= form.submit "Criar Produto", class: "mt-1 btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/produtos/show.html.erb
<h2 class="text-secondary text-center mb-3">Resultados da Pesquisa: <%= params[:nome] %></h2>
<div class="container w-50">
  <%= render 'produto', obj: @nome %>
  <% if @nome.empty? %>
    <h4 class="text-center text-secondary">Nenhum produto com este nome encontrado</h4>
  <% end %>
</div>

app/views/shared/_errors.html.erb
 <% if obj.errors.any? %>
  <div class="container w-100">
    <div class="alert alert-danger alert-dismissible fade show text-start" role="alert">
      Os Seguintes erros ocorreram:
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>